### ISSUE TITLE
Growl demo does not seem to work

### ISSUE THREAD

**Issue by jepsar** [TheCoder4eu/BootsFacesWeb#43] opened 2017-05-03 20:17 UTC
https://showcase.bootsfaces.net/forms/Growl.jsf

I'm clicking the buttons and nothing seems to happen.

No errors in my JS console.

Network shows a request with 200 response:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<partial-response id="j_id1"><changes><update id="growlForm"><![CDATA[
<form id="growlForm" name="growlForm" method="post" action="/forms/Growl.jsf" enctype="application/x-www-form-urlencoded">
<input type="hidden" name="growlForm" value="growlForm" />
<button id="growlForm:j_idt177" name="growlForm:j_idt177" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" onclick="PrimeFaces.ab({s:&quot;growlForm:j_idt177&quot;,u:&quot;growlForm&quot;});return false;" type="submit"><span class="ui-button-text ui-c">Info</span></button><script id="growlForm:j_idt177_s" type="text/javascript">PrimeFaces.cw("CommandButton","widget_growlForm_j_idt177",{id:"growlForm:j_idt177"});</script><button id="growlForm:j_idt178" name="growlForm:j_idt178" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" onclick="PrimeFaces.ab({s:&quot;growlForm:j_idt178&quot;,u:&quot;growlForm&quot;});return false;" type="submit"><span class="ui-button-text ui-c">Warn</span></button><script id="growlForm:j_idt178_s" type="text/javascript">PrimeFaces.cw("CommandButton","widget_growlForm_j_idt178",{id:"growlForm:j_idt178"});</script><button id="growlForm:j_idt179" name="growlForm:j_idt179" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" onclick="PrimeFaces.ab({s:&quot;growlForm:j_idt179&quot;,u:&quot;growlForm&quot;});return false;" type="submit"><span class="ui-button-text ui-c">Error</span></button><script id="growlForm:j_idt179_s" type="text/javascript">PrimeFaces.cw("CommandButton","widget_growlForm_j_idt179",{id:"growlForm:j_idt179"});</script><button id="growlForm:j_idt180" name="growlForm:j_idt180" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" onclick="PrimeFaces.ab({s:&quot;growlForm:j_idt180&quot;,u:&quot;growlForm&quot;});return false;" type="submit"><span class="ui-button-text ui-c">Fatal</span></button><script id="growlForm:j_idt180_s" type="text/javascript">PrimeFaces.cw("CommandButton","widget_growlForm_j_idt180",{id:"growlForm:j_idt180"});</script><button id="growlForm:ref" name="growlForm:ref" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" onclick="PrimeFaces.ab({s:&quot;growlForm:ref&quot;,u:&quot;growlForm&quot;});return false;" type="submit"><span class="ui-button-text ui-c">Specific (With custom animation)</span></button><script id="growlForm:ref_s" type="text/javascript">PrimeFaces.cw("CommandButton","widget_growlForm_ref",{id:"growlForm:ref"});</script>
</form>]]></update><update id="j_id1:javax.faces.ViewState:0"><![CDATA[-3433417538762328530:-8746944569053880865]]></update></changes></partial-response>
```

**Comment by stephanrauh** [comment] 2017-05-03 20:27
I suppose that's a duplicate of https://github.com/TheCoder4eu/BootsFaces-OSP/issues/748. I've fixed the bug in the core library, but we updated neither the core library nor the showcase yet.

Feel free to re-open the ticket if my diagnosis is wrong.

**Closed as completed by stephanrauh** 2017-05-03 20:27 UTC
Labels: bug
